### ISSUE TITLE
Problem filling orders

### ISSUE THREAD

**Issue by brubrant** [geraked/metatrader5#1]
Hi,

First all congrats on the amazing work and thanks for letting this public!

When trying to run some tests with my broker I got the following error:
_failed market buy 0.01 EURUSD [Unsupported filling mode]_

I managed to walk-around this by setting the filling mode on the "EAUtils" and compiling the bot again. 
Using an approach similar to [this one](https://www.mql5.com/en/forum/441823).

Just wanted to let you know. Maybe you want to implement this option (on a more elegant way).

BTW: I'm using Pepperstone.

Thanks again!

**Comment by geraked** [comment]
Thanks for your kind words! I appreciate your feedback and will fix it in the next update.

**Comment by brubrant** [comment]
Hi, I tried the new versions today and still getting the same Error.

I saw you changed the EAUtils, but got the error anyway (failed market sell 0.01 USDJPY [Unsupported filling mode])

I think a good approach would be allow the user to chose the filling mode on the input screen...

Thanks in advance

**Comment by geraked** [comment]
Hi, as you recommended, an input has just been added to explicitly set the filling order type. I hope this will resolve the issue for these types of brokers. Please review it and provide feedback to ensure it works.
I appreciate your attention.

**Comment by brubrant** [comment]
Hi @geraked . Now I was able to set the filling type to IOK and it worked on my broker!

Thanks. You rock!

**Comment by vishal12212001** [comment]
Hi brother Thanks for shear Useful concept of trading .\
i am trying to BT but i got below indicator error .
 


2024.01.08 17:38:20.460	CEZLSMA.ex5::Indicators\ChandelierExit (AUDUSD,H1)	cannot load custom indicator '::Indicators\Examples\Heiken_Ashi.ex5' [4802]
